### ISSUE TITLE
Feature Request: Display contents of local markdown file

### ISSUE THREAD

**Issue by snoblenet** [allister-grange/startertab#22]
I'd love to add a panel that displays the contents of a local markdown file

**Comment by allister-grange** [comment]
I've merged in the PR, let me know if you're happy with the end result :)

**Comment by snoblenet** [comment]
Awesome! I'm not seeing it, however. 
![image](https://user-images.githubusercontent.com/62277/199122391-8e035cf6-b1e5-4448-8335-f82a7f1530c5.png)

**Comment by allister-grange** [comment]
You can change the type of any tile by going into that tile in the sidebar and changing the "Tile Type" option, see below 

![Annotation 2022-11-01 132327](https://user-images.githubusercontent.com/18430086/199133047-22433ee4-ccd1-4f8c-9f94-600c735b6569.png)

**Comment by snoblenet** [comment]
Oh cool. Thanks. I'll have to select a file that does not use relative links, but it works well. 
![image](https://user-images.githubusercontent.com/62277/199135953-b37385c7-5b6e-4b3f-b517-1434111f2ac1.png)
