### ISSUE TITLE
large font overflow bug

### ISSUE THREAD

**Issue by masukomi** [allister-grange/startertab#25]
Set font size to 20, and MINIMUM font size to 20. Shouldn't matter if you're using FF or Chrome. 

An accessibility issue for folks like me who need large fonts. 

![CleanShot 2022-10-27 at 12 28 58@2x](https://user-images.githubusercontent.com/2829/198346940-fe49a9bb-2c60-4296-9c84-3f4d05d7595b.png)

**Comment by allister-grange** [comment]
I had never browsed the internet with a font size like that, thank you for the enlightenment! It really changes the formatting for a lot of sites.

So as you can see below, I've fixed the overflow. I've also tweaked the Time Tile and the heights of the tiles on smaller screen sizes, at it didn't look acceptable with my font size turned up. 

Let me know what you think! 

<img width="322" alt="image" src="https://user-images.githubusercontent.com/18430086/198848910-2ca514d3-ade6-4515-a15b-812f74587bb2.png">

**Comment by allister-grange** [comment]
Actually, I didn't like that solution, this is much better

<img width="332" alt="image" src="https://user-images.githubusercontent.com/18430086/198851039-767e75df-796d-4d2d-8320-2ee8fed4e05a.png">

**Comment by allister-grange** [comment]
@masukomi I am going to close the issue, hopefully you're happy with the solution. 

Let me know if you're not!
