### ISSUE TITLE
Bug: Downloading new themes doesn't work on safari

### ISSUE THREAD

**Issue by noahgaertner** [allister-grange/startertab#36]
On safari, if you save a theme in the public theme gallery, you get a green popup at the top saying the theme was saved, and it shows as saved in the public theme gallery even after a browser restart, but it doesn't show up as an option in the theme selector on the actual homepage, even after a restart.

Expected Behavior: it shows up & applies successfully

**Comment by allister-grange** [comment]
Interesting, this is working for me just fine in Safari. As you can see in my screenshot, I downloaded the "Minimal Blue" theme on Safari without trouble.

Are you able to tell me the name of the theme you're having trouble with? Do you see the downloaded theme in your personal themes tab?


<img width="1207" alt="image" src="https://user-images.githubusercontent.com/18430086/220009818-0c97ca1a-e2b3-4a5b-aad2-5ec35e61cce0.png">

**Comment by noahgaertner** [comment]
Minimal Blue appears to work for me as well - the themes I had issues with were

- Samurai Nights
- Monet Sunrise
- City Life
- Dark Office
- Chill Spot

**Comment by noahgaertner** [comment]
I just deleted cookies and those seem to now work as well, so I'm going to close this issue

no idea what was wrong before, but oh well I guess?

**Comment by allister-grange** [comment]
Perfect, glad to hear it's sorted

**Comment by allister-grange** [comment]
I don't know how the cookies would be related, I'd get it if it was the localstorage 🤷
