### ISSUE TITLE
Import/Export Config as XML

### ISSUE THREAD

**Issue by Logvin** [allister-grange/startertab#39]
I have multiple computers, work and personal. I would love a button where I can customize my Startertab, then export the config to a file, like an XML file, then import that file on another computer to mirror my Statertab on that machine.

**Comment by allister-grange** [comment]
The intention was that people would publicly list there themes at [the theme martketplace](https://startertab.com/themes#public).

I will still make this feature though, I can see why you would want to export/import your own files without having to go through everyone else seeing them.

**Comment by Logvin** [comment]
So a use case I was thinking is that I work on a team of ~150x people. We have a LOT of internal bookmarks as most of our tools are web-based. When someone new gets hired they get... an Excel document copy of them. Yuck. I would love to shoot them a XML file w/ startertab.com and have them simply import it and bam... they get all the internal boomarks, and other widgets that might help them get going, like RSS feeds to industry blogs, etc.

That, and I have multiple computers and do not want to recreate my tab for each one.

**Comment by allister-grange** [comment]
I love this idea! I’ll for sure implement the export/import function, there
is definitely utility there.

I’ve also just finished developing a Chrome extension for the site, I just
need to take some demo videos and screenshots then I will submit it to the
store. This will streamline the process of using StarterTab, so it would be
much easier to share the site with your colleagues once that’s done.

**Comment by allister-grange** [comment]
@Logvin all merged and the feature is now in prod 🙂

You'll see the buttons in the sidebar now. Let me know if you find any issues with it!

The Chrome Extension is finished and currently waiting for review from the Chrome Extension team. Once that's live it'll be much easier to onboard your team with the application. I'll put up an update/toast in the app once that's up and running. 

<img width="318" alt="image" src="https://user-images.githubusercontent.com/18430086/222869661-d0eaf4df-e698-449c-8665-1ad240b4ac88.png">

**Comment by Logvin** [comment]
awesome progress! I went through and customized a theme and saved it. When I tried to import it, it complained about the name. I had to go into the file and manually edit the theme name away from whatever the original template was. Not hard, but not user friendly.

The import worked partially, but it missed some stuff.

Exported this:
![image](https://user-images.githubusercontent.com/13814907/222875787-7a5ec0f9-df40-4c77-8776-bf5a401efb05.png)

Imported and it looked like this:
![image](https://user-images.githubusercontent.com/13814907/222875808-6919914f-3156-496e-a92c-587d668b95d9.png)

**Comment by allister-grange** [comment]
Apologies for the confusion around the theme name on the import. The application doesn't like duplicate theme names as they're a unique identifier for the theme, so I wouldn't allow you to import a theme that you already had. 

I've changed the code now so that when you import a theme with a matching theme name already in your StarterTab, you get a new theme with "copy" appended to the name.

To your with some settings not coming across, of course I am unable to replicate it! Are you able to please tell me your OS and what browser you're using? There' also a change that the JSON was muddled with when you changed the theme name (although it's quite unlikely), so maybe you want to give it another shot?

**Comment by Logvin** [comment]
you don't need to apologize for anything my friend!

I use firefox on Ubuntu Desktop. I have a windows PC ill have access to tonight that i can double check later. I mainly test by opening a private window.

**Comment by allister-grange** [comment]
Ahhh okay I am able to replicate the issue on Firefox 🙂

All that was needed was a quick refresh on the tab and then you will see all the data there! The tiles are in their original "new" tile state, but the data behind them is all there. I might programmatically force a refresh of the tab after an import. 

Let me know if after you give a refresh of the tab that it all looks okay 🙂

**Comment by Logvin** [comment]
looks awesome. thanks man!

**Comment by allister-grange** [comment]
No worries man! Thanks for the feedback/suggestions, if you have any else just send em through.

I've added in the refresh now. Let me know if I can close the ticket.

**Comment by Logvin** [comment]
works awesome. close it down!

**Comment by allister-grange** [comment]
@Logvin did you ever end up using it at your work? 

Let me know if you need anything more to make this a possibility. There's been quite a lot of work done on the site since this issue!
