### ISSUE TITLE
Optional Title for Bookmark List (Feature Request)

### ISSUE THREAD

**Issue by Logvin** [allister-grange/startertab#43]
Would love to have the ability to have a title for my bookmarks list. I imagine it would look exactly like the RSS Feed title, with the underline, but customizable to whatever I want to call my bookmarks. Example like "Dev Tools" or "Photography Sites" to help better organize my list.

**Comment by allister-grange** [comment]
Set the title in the sidebar options :) 

You'll see an option there now for a title, it's the same with the Bookmark and RSS Feed tiles

<img width="307" alt="image" src="https://user-images.githubusercontent.com/18430086/223930464-78f9e0d6-364b-4bae-9d7e-74c5aa8655db.png">
