### ISSUE TITLE
Twitter tokens in strava API?

### ISSUE THREAD

**Issue by tadwohlrapp** [allister-grange/startertab#47]
Just stumbled upon this while checking out your implementation of the Strava API:

https://github.com/allister-grange/startertab/blob/63cbfac88ab65410b45d8c64fd06a499e2d86f3d/src/pages/api/strava/index.ts#L272

https://github.com/allister-grange/startertab/blob/63cbfac88ab65410b45d8c64fd06a499e2d86f3d/src/pages/api/strava/index.ts#L280

Surely it's a typo, no?

**Comment by allister-grange** [comment]
Big typo, obviously a copy/paste mistake!

Thanks for noticing, I will fix it up 🙂 unless you want to make a PR and get the brownie points?

**Comment by tadwohlrapp** [comment]
@allister-grange Sorry, completely missed the notification. Thanks for fixing it! :)
