### ISSUE TITLE
Can't search or open search engine

### ISSUE THREAD

**Issue by nahuelarg86** [allister-grange/startertab#48]
Hi, I'm having an issue with the startertab chrome extension. When I try to search anything on the search bar, I press enter and nothing happens. Also, when I click on one of the search engines, I get a "www.google.com refused to connect." page (same with the other engines). Do you have any guidance on how to solve this?
Thanks!

**Comment by allister-grange** [comment]
Ahhh, yes I see the issue. I will get onto it 🙂

**Comment by allister-grange** [comment]
All fixed!
