### ISSUE TITLE
Spotify widget dosent work.

### ISSUE THREAD

**Issue by Magniquick** [allister-grange/startertab#61]
The spotify widget does pop up, but the next/play/pause/previous actions fail to execute.
It is able to get which song is currently playing, however.
Looking at the network requests, It shows "Failed to pause or play song" with a 403 error.

**Comment by allister-grange** [comment]
Hi, is this in your local environment, like your other ticket? Or is this on [StarterTab](https://startertab.com)?

**Comment by Magniquick** [comment]
On the website/extension.

**Comment by Magniquick** [comment]
This also happens on my local environment, both on Firefox and chrome.

**Comment by allister-grange** [comment]
Hmm I suspect there may have been a permissions issue during the oAuth when you allowed your Spotify to integrate with StarterTab.

If you could please remove your access to StarterTab from Spotify. Account -> Manage Apps. 

<img width="883" alt="image" src="https://github.com/allister-grange/startertab/assets/18430086/77d45a36-740d-448e-aa3a-c092ce53bea6">

Then please remove both the `spotifyAccessToken` and the `spotifyRefreshToken` cookies from your tab. 

Then after a page refresh, you should see the `Continue with Spotify` button, give it another shot and let me know how it goes!

This feature is still operational on my tab, so I am suspicious something failed in the auth process with yours.

**Comment by allister-grange** [comment]
Hmmm, those are definitely the correct permissions. I was just about to ask you for a screenshot of that, thank you!

What browser / operating system are you using? That shouldn't affect it, as as you said, the network call is going out and it's getting a 403. Just for the sake of clearing all options however, I will try to replicate the issue matching your system. 

My guess would be that there's some setting on your Spotify account that is blocking Third Party control somehow? I've googled and looked through the Spotify settings and can't see anything however.

**Comment by Magniquick** [comment]
Happens both on Firefox and chrome - with no extensions.
on macos, disabling the firewall that I use (lulu) or removing spicetify has no effect.
Enabling the entire range of apis in the spotify developer dashboard dashboard nor adding my account to the user management section of spotify works.
I checked the requests logs and there seems to be nothing off - but I'm far from a web dev, so idk
any logs / anything else you want ?

**Comment by Magniquick** [comment]
Wait, do you use Spotify premium by any chance ?

**Comment by Magniquick** [comment]
There are ways around this, but they look hacky : /
https://github.com/CriticalElement/spotify-free-api-player
https://github.com/FrostBreker/spotify-private-api
mainly involving the private api : (

**Comment by allister-grange** [comment]
Yup that'll be it, I just confirmed the issue by creating my own free account. I don't believe it was only premium accounts in the past when I set up this feature, there must have been some spammage or something on Spotify's end to result in that.

Apologies, I won't be going down the private API route, I don't want to jeopardize the project in any way. 

I will 100% get onto the 12 hour clock! I'll make a setting you can toggle on the clock tile to switch it between 12/24 hours. I'll also add an option to remove the buttons on the Spotify tile as well. I see you've already left the suggestion on the suggestions page, thanks for that! 

Sorry that Spotify are blocking this! I'm glad that it wasn't some weird bug with my code though haha. I'll close the ticket :)

**Comment by allister-grange** [comment]
I've added in the 12h option on the time tile now, just long click on the tile, then you'll see the new button in the bottom right. I'll update Spotify in the coming week :)

<img width="238" alt="image" src="https://github.com/allister-grange/startertab/assets/18430086/2f101487-415e-41f0-9242-97bc589ebde2">

**Comment by Magniquick** [comment]
> in the past when I set up this feature, there must have been some spammage or something on Spotify's end to result in that.

Yep, has broken some of my workflows too (with raycast : / )
> Apologies, I won't be going down the private API route, I don't want to jeopardize the project in any way.
Of course !
> I will 100% get onto the 12 hour clock! I'll make a setting you can toggle on the clock tile to switch it between 12/24 hours. I'll also add an option to remove the buttons on the Spotify tile as well. I see you've already left the suggestion on the suggestions page, thanks for that!

Thanks a loot !
> Sorry that Spotify are blocking this! I'm glad that it wasn't some weird bug with my code though haha. I'll close the ticket 

As mentioned before: a slider to toggle the (useless for me) playback buttons would be nice !
Either way, Thanks for all that you do !
(I'd love to help development, but alas, the pains of a backend dev :P )

**Comment by allister-grange** [comment]
I've added in an option to hide the Spotify media controls, check it out in the sidebar!

I'll also add a couple of the tweaks you put forward for the time tile on the suggestions page, I've only done the 12/24 switch for now, thanks for contributing some great ideas!

**Comment by allister-grange** [comment]
More options done for the time tile - check out the sidebar
