### ISSUE TITLE
Unable to setup spotify in local enviorment.

### ISSUE THREAD

**Issue by Magniquick** [allister-grange/startertab#62]
After following the instructions in the readme, I tried to setup the spotify widget.
however, Even after adding the uri to the spotify allowed uri list, the callback fails with:
``No encryption key found in environment variables``
(P.S. : where do you obtain a weather api key  from ?)

**Comment by allister-grange** [comment]
You will want to populate the `TOKEN_ENCRYPT_KEY` value in the `.env.local` to a random string. This is used to encrypt the cookies in rest your browser.

The weather API that I am using is [found here](https://www.weatherapi.com/).

**Comment by Magniquick** [comment]
Hey, that works perfectly, thanks a lot man !
(Pssst: wanted to tell you that your startpage with a lil bit of theming got to ~50 hearts in the unixporn discord server. For reference, that's the highest a rice has gotten in the past two weeks or so, with there being around 10 posts a day. Thanks a lot man !)
<img width="2352" alt="Screenshot_2024-01-25_at_1 21 05_AM" src="https://github.com/allister-grange/startertab/assets/67406856/c7a81139-95d2-49d5-a242-03ed855808ff">

**Comment by allister-grange** [comment]
Thank you so much for posting the tab in the server! Any natural spreading-the-word of the site is much appreciated. I of course want as many users as possible, and it's hard to organically grow something without spamming it on the internet everywhere. 

You'll be responsible for this uptick in visitors! 

<img width="915" alt="image" src="https://github.com/allister-grange/startertab/assets/18430086/79276844-6810-47de-a5f1-60e4c4e953aa">

**Comment by Magniquick** [comment]
You deserve it man !
