### ISSUE TITLE
(Potentially) Broken special character handling ?

### ISSUE THREAD

**Issue by Magniquick** [allister-grange/startertab#64]
<img width="265" alt="Screenshot 2024-03-03 at 3 51 43 PM" src="https://github.com/allister-grange/startertab/assets/67406856/d3836ffb-edc4-4344-99e8-473cd839111e">

The &amp is supposed to be just a &.

**Comment by allister-grange** [comment]
Thanks for spotting this. I've updated the HackerNews, Reddit and Twitter tiles. 


Before

![image](https://github.com/allister-grange/startertab/assets/18430086/04a159b2-aa0e-4e8c-ad94-09e2618d3352)


After 

![image](https://github.com/allister-grange/startertab/assets/18430086/d224ca3d-3f31-4534-8f28-5514b8743da0)
