### ISSUE TITLE
StarterTab frequently reverts to older layout

### ISSUE THREAD

**Issue by trlef19** [allister-grange/startertab#65]
Many times, it just goes to my previous layout (old wallpaper and tiles). Refreshing fixes it sometimes

**Comment by allister-grange** [comment]
Hey @trlef19, do you have any more details on this? I personally haven't seen this kind of issue before. 

Are you to provide the browser you're using? If this keeps happening you could send through your theme settings if you're comfortable with that

**Comment by trlef19** [comment]
Hello, I'm using Microsoft edge. I've changed my layout to a new wallpaper and a bit different tiles. When I open up the browser, it's the new one. When I visit a webpage and then press the home button, it reverts to the old one (previous wallpaper and colors) and stays like this until I close the browser:))

**Comment by allister-grange** [comment]
Is the home button for sure linking to https://startertab.com? It may be that you have two instances running, maybe one at "https://www.startertab.com" and one at "https://startertab.com".

Can you please confirm that the urls are the same when visiting the site through the home button vs whatever method you have going to make this your new tab on Edge? Thank you!

**Comment by trlef19** [comment]
Hello, yes. Im actually using your extension for the "new tab". 
Here is a video of what happens when i press "home"

https://github.com/allister-grange/startertab/assets/82327147/687a8211-5e84-4196-b7bf-794a194151d1
