### ISSUE TITLE
Favorite Links Tile stores Links incorrectly

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [allister-grange/startertab#66]
Whenever I add a link in the Favorite Links Tile, the link automatically gets saved as "startertab.com/[link]", and because that page obviously does not exist, the link stored (as a bookmark in the Tile) is pretty much useless. Below is a demonstration:

https://github.com/allister-grange/startertab/assets/74773615/1ea77eef-3192-4ce1-8a24-5094646958ed

Thanks.

**Comment by trlef19** [comment]
it needs the https for some reason :))

**Comment by allister-grange** [comment]
Hey @trlef19, thanks for raising this! 

I've fixed it now so that the links will always go to the external sites, regardless of wether they start with `http` or not
