### ISSUE TITLE
Weather API widget seems to be Bugged.

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [allister-grange/startertab#67]
The weather widgets API seems to be bugged, because it is displaying incorrect data.

It is night in my area, yet it shows Sunny here. Sometimes the degrees are off (usually by 1 degree but that is not the major issue here, as I suppose it is using a different API than Weather.com's)

Weather Widget:
![image](https://github.com/allister-grange/startertab/assets/74773615/21c460a0-5041-4148-9126-f699baefcfc7)

Phone weather app:
![image](https://github.com/allister-grange/startertab/assets/74773615/ccf0a9a2-df28-4f1e-87a6-c6133022a335)

Thanks,
Me.

**Comment by allister-grange** [comment]
Hey @Ujjwal-Rohilla the reason for the sun is to show that there's no rain that night i.e. that it's a clear sky.

You're correctly, ideally this would be a moon for the night. I'll have a look over the icons and see if I can't improve them.

**Comment by allister-grange** [comment]
Fixed 🙂

![image](https://github.com/allister-grange/startertab/assets/18430086/32a7ab9c-9812-4152-8636-8c78a7823260)
