### ISSUE TITLE
Build show errors/warnings

### ISSUE THREAD

**Issue by Magniquick** [allister-grange/startertab#69]
Hola there, it's me again !
Was trying to make a docker container for this, but some errors/warnings pop up while building
The website itself does work, but I want to make sure that this does not affect anything else
seems related to [vercel/next.js#48192 (comment)](https://github.com/vercel/next.js/discussions/48192?sort=top#discussioncomment-7300963)
the errors:
```
Warning: React Hook useEffect has missing dependencies: 'startTimer' and 'updateTime'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
(.....)
 Warning: React Hook useEffect has a missing dependency: 'growBonsai'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
(.....)
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
(.....)
Static worker unexpectedly exited with code: null and signal: SIGINT (repeated ~14 times)
```
Is it fine to ignore these ?

**Comment by allister-grange** [comment]
Hey @Magniquick, the warnings are for sure fine, they're just poor state management on a couple of the trickier tiles. I can fix those up with comments on the next push that I make.

As for the `Static worker unexpectedly exited with code: null and signal: SIGINT` I will take a look into that. It's obviously not preventing the site from running, but it doesn't look good!

**Comment by allister-grange** [comment]
@Magniquick I fixed the useEffect warnings, the `Static worker unexpectedly exited with code: null and signal: SIGINT` issue is very ambiguous from a quick look through the [thread](https://github.com/vercel/next.js/discussions/48192), don't have the time to pursue it for now as it's not breaking anything, you're free to have a look :) 

Let me know if you need anything else
