### ISSUE TITLE
Startertab connects to https://startertab.com even when locally hosted

### ISSUE THREAD

**Issue by Magniquick** [allister-grange/startertab#71]
![ng](https://github.com/allister-grange/startertab/assets/67406856/b1edc4e0-f6a6-42ac-8cb1-05c881cbae7f) \
Seems like analytics, but still, it would be nice if the locally hosted version was completely independent from the hosted version.

**Comment by allister-grange** [comment]
It's hooking through to the analytics as you say, it was rushed to avoid the ridiculous charges I was getting through Vercel analytics. 

I'll action this, thanks for pointing it out.

**Comment by allister-grange** [comment]
Hey @Magniquick it looks like I did actually exclude analytics from dev environments (thanks past me). 

What url is being called exactly here? There are some references to the production site for some images, in prod I want to point to urls for performance purposes, it's not worth the hassle to remove these for dev. There's also another reference to the prod site for the preview of the landing page, which again isn't going to go.

Here's the code for the analytics below: 

![image](https://github.com/allister-grange/startertab/assets/18430086/994dfb6b-bca7-406e-9984-99ac2b21efcd)

Let me know if you want some of this changed, you're create a PR if you want for this, open to suggestions and your thoughts!

**Comment by Magniquick** [comment]
I am using a prod environment right now. Would you be fine with an environment variable called ANALYTICS_ENABLED or so, replacing the production var ?

**Comment by allister-grange** [comment]
So what is the end goal here? Is this to do with containerisation? 

It wouldn't take long to add this env variable in, but I'm slightly skeptical of its purpose. I hope I am coming across as curious here and not rude!

If you're wanting to go down the self-hosted route, you could always fork? It would be sad to lose a user though!

**Comment by Magniquick** [comment]
> So what is the end goal here?  

Personally, I think it'd be pretty cool if anyone could self host this without relying on the site itself
Say, in case you lose interest or feel that this is getting expensive or so, and decide to shut the site down, having a well made self hosted option would make it easy to keep using this. Even if that does not happen, it would give me (and others) peace of mind knowing that that is possible.  

Plus, I like the feeling of services I depend on running on my own system: P
> you could always fork

Alas, I only do a bit of python. I would not be able to maintain such a thing : (

> and not rude!

You are one of the most nicest maintainers that I have ever met. You could have just said you are not interested in maintaining such a thing and closed this off any second. 
Either way, thanks for your patience and time.

**Comment by Magniquick** [comment]
Closing this as I've made a fork without the tracking.

**Comment by allister-grange** [comment]
Sorry @Magniquick, I know you didn't want to fork. I've been on holiday without my laptop the last week.

I will get around to this change in the next day or so!

**Comment by Magniquick** [comment]
Na, have fun !
It isn't an emergency or anything lol

(P.S.: would be grateful if you tell me how to set up the favicon, like the live site (even without extensions) does. The next.js docs mention a (app)[https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#image-files-ico-jpg-png] directory and adding things to the /app route segment. Would be cool if you could point me to the right files and directories : P )

**Comment by allister-grange** [comment]
All done now, just set the following env variable:

`ANALYTICS_ENABLED=false`

**Comment by Magniquick** [comment]
still seems to try to use /_vercel/insights/script.js : /

**Comment by Magniquick** [comment]
@allister-grange mind reopening or closing as wontfix ?
