### ISSUE TITLE
Bonsai broken at base : (

### ISSUE THREAD

**Issue by Magniquick** [allister-grange/startertab#74]
<img width="263" alt="Screenshot 2024-05-05 at 8 07 37 PM" src="https://github.com/allister-grange/startertab/assets/67406856/0f078100-e92b-4441-8990-1988312c6989">    

(Believe this will be the last issue from me !)

**Comment by allister-grange** [comment]
[Fixed!](https://github.com/allister-grange/startertab/commit/0aecb0a8496503b02c5c7a4a984f019f743cc6cb)

**Comment by allister-grange** [comment]
Make as many issues as you can! I appreciate the feedback 🙂
