### ISSUE TITLE
[Suggestion] Add sub-categories/Folders for ToDo List

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [allister-grange/startertab#75]
Feature Request to add capability of sub folder/category in ToDo List. Right now my ToDo list is a bit messy, with my personal work in between school work and so on, so I would like a feature that adds something shown in the Image attached below (ignore my poor MS Paint skills lol). I feel this would make my work more organized
![image](https://github.com/allister-grange/startertab/assets/74773615/09715fc8-08b9-4ba3-9a26-cb0145cebb17)

Thanks!

**Comment by allister-grange** [comment]
@Ujjwal-Rohilla  fantastic idea, I'll work on it!

**Comment by allister-grange** [comment]
@Ujjwal-Rohilla I've released in now, let me know what you think
